"""drop unused flagged_ingredients column

Revision ID: 264ffa7ff30b
Revises: 4099a67798a3
Create Date: 2026-08-06 10:08:52.474082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264ffa7ff30b'
down_revision = '4099a67798a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('flagged_ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged_ingredients', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
