"""add profile table

Revision ID: 4099a67798a3
Revises: bf5621ac5b30
Create Date: 2026-08-05 11:55:44.092571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4099a67798a3'
down_revision = 'bf5621ac5b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skin_type', sa.String(length=200), nullable=True),
    sa.Column('preferred_brands', sa.Text(), nullable=True),
    sa.Column('preferred_ingredients', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
