"""add sleep schedule fields to profile

Revision ID: b0652e7a5698
Revises: 264ffa7ff30b
Create Date: 2026-08-08 16:51:26.681982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0652e7a5698'
down_revision = '264ffa7ff30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wake_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('sleep_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('sleep_time')
        batch_op.drop_column('wake_time')

    # ### end Alembic commands ###
